<<<<<<< HEAD

let dataFarde = [
    ['nummer',  'coria '                                                                                                    , 'pdf'                                                                                                          , 'web'                                                                                                              , 'mp3'                                                                                      , 'titel'                           ],
    [  '0003',  '<a href=./0003_HijDieDeBlindenWeerLietZien.html><img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0003_4_HijDieDeBlindenWeerLietZien.pdf><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Hij die de blinden weer liet zien'       ],
    [  '0004',  '<a href=./0004_PelgrimsVanHoop.html>            <img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0004-4_PelgrimsVanHoop.pdf            ><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Pelgrims van hoop'                       ],
    [  '0025',  '<a href=./0025_Sanctus.html>                    <img src="./quaver.svg"  width="20" height="20"></img></a>', ''                                                                                                             , ''                                                                                                                 , ''                                                                                         , 'Sanctus'                                 ],
    [  '0035',  '<a href=./0035_KwaadEnZorgen.html>              <img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0035-2_KwaadEnZorgen.pdf              ><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Kwaad en zorgen'                         ],
    [  '0041',  '<a href=./0041_Pelgrimslied.html>               <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Pelgrimslied'                            ],
    [  '0043',  '<a href=./0043_GijSchreefMijnNaam.html>         <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Gij schreef mijn naam'                   ],
    [  '0059',  '<a href=./0059_LichtVanDeWereld.html>           <img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0059-4_LichtVanDeWereld.pdf           ><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Licht van de wereld'                     ],
    [  '0080',  '<a href=./0080_HeiligHeiligHeilig.html>         <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Heilig, heilig, heilig'                  ],
    [  '0082',  '<a href=./0082_BlijfMijNabij.html>              <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Blijf mij nabij'                         ],
    [  '0088',  '<a href=./0088_LooftDeHeer.html>                <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Looft de Heer'                           ],
    [  '0089',  '<a href=./0089_SingJoyful.html>                 <img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0089-2_SingJoyfulPraise.pdf           ><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Sing Joyful'                             ],
[ '0109' ,'<a href=./0109_GaMeeMetOns.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga mee met ons' ], 
[ '0112' ,'<a href=./0112_GloriaSeiDirGesungen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gloria sei dir gesungen' ], 
[ '0115' ,'<a href=./0115_HerdersHijIsGeboren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Herders Hij is geboren' ], 
[ '0121' ,'<a href=./0121_EerZijGod.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Eer zij God' ], 
[ '0126' ,'<a href=./0126_GodLeerdeOnsDeLiefde.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'God leerde ons de liefde ' ], 
[ '0140' ,'<a href=./0140_Da_pacem_domine.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Da pacem domine ' ],
[ '0169' ,'<a href=./0169_DonaLaPace.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0169-4_DonaLaPace.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Dona la pace ' ],
[ '0192' ,'<a href=./0192_BekommerdOmVrede.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Bekommerd om vrede ' ], 
[ '0197' ,'<a href=./0197_Alta_Trinità_beata.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Alta Trinità beata ' ], 
[ '0198' ,'<a href=./0198_DeSteppe.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'De steppe zal bloeien ' ], 
[ '0213' ,'<a href=./0213_GaJeAllenMetOnsMee.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga je allen met ons mee' ], 
[ '0220' ,'<a href=./0220_WaarJeWoontOpDezeWereld.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Waar je woont op deze wereld' ], 
[ '0237' ,'<a href=./0237_ZomaarEenDak.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zomaar een dak' ], 
[ '0247' ,'<a href=./0247_KindOnsGeboren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kind ons geboren' ], 
[ '0260' ,'<a href=./0260_DeGeestDesHeren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'De geest des heren ' ], 
[ '0266' ,'<a href=./0266_Here_der_Heren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Here der Heren' ], 
[ '0284' ,'<a href=./0284_JijHebtEenNaam.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jij hebt een naam' ], 
[ '0286' ,'<a href=./0286_GeprezenZijOnzeGod.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Geprezen zij onze God ' ], 
[ '0289' ,'<a href=./0289_IkZieDeHemelOpengaan.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0289-4_IkZieDeHemelOpengaan.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Ik zie de hemel opengaan ' ],
[ '0300' ,'<a href=./0300_LuisterHeer.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0300-4_LuisterHeer.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Luister Heer ' ],
[ '0301' ,'<a href=./0301_NieuweMensInOnsGeboren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0301-4_NieuweMensInOnsGeboren.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Nieuwe mens in ons geboren' ],
[ '0303' ,'<a href=./0303_LiedAanHetlicht.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Lied aan het licht ' ], 
[ '0309' ,'<a href=./0309_StadBovenWolken_HeerlijkVisioen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Stad boven wolken / Heerlijk visioen ' ], 
[ '0318' ,'<a href=./0318_Zing_met_mij_Halleluja.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zing met mij Halleluja' ], 
[ '0325' ,'<a href=./0325_VredeVoorJou.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede voor jou' ], 
[ '0337' ,'<a href=./0337_MariaDieZoude.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Maria die zoude naar Bethlehem gaan' ], 
[ '0341' ,'<a href=./0341_LichtOntlokenAanHetDonker.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0341-3_LichtOntlokenAanHetDonker_BZJ824.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Licht ontloken aan het donker' ],
[ '0344' ,'<a href=./0344_PrijzenWijDeHeer.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Prijzen wij de Heer' ],
[ '0345' ,'<a href=./0345_HereJezusOmUwWoord.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Here Jezus om uw woord' ], 
[ '0346' ,'<a href=./0346_Esengo.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Esengo ' ], 
[ '0347' ,'<a href=./0347_EensKomtDeDagWaarvanWijDromen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Eens komt de dag waarvan wij dromen' ], 
[ '0349' ,'<a href=./0349_LichtInOnzeOgen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Lichtin onze ogen' ], 
[ '0351' ,'<a href=./0351_Eer_aan_onze_God.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0351-4_EerAanOnzeGod.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Eer aan onze God' ],
[ '0355' ,'<a href=./0355_GegroetJijDieHierKomtOmLicht.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gegroet jij die hier komt om licht' ], 
[ '0359' ,'<a href=./0359_KleinPaaslied.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0359-4_KleinPaaslied.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Klein Paaslied' ],
[ '0361' ,'<a href=./0361_StemVanVuur.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0361-4_StemVanVuur.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Stem van vuur' ],
[ '0362' ,'<a href=./0362_OmdatHijLeeft.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Omdat hij leeft ' ],
[ '0363' ,'<a href=./0363_ZEGEN_VAN_SINT-FRANCISCUS.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Zegen van Sint-Franciscus' ],
[ '0369' ,'<a href=./0369_WijGelovenInHetLeven.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Wij geloven in het leven ' ],
[ '0373' ,'<a href=./0373_ZONNELIED_VAN_FRANCISCUS.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zonnelied van Franciscus ' ], 
[ '0376' ,'<a href=./0376_DonaNobisPacem.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Dona nobis pacem' ], 
[ '0381' ,'<a href=./0381_Thuma_Mina.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0381-4-ThumaMina.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Thuma Mina' ],
[ '0386' ,'<a href=./0386_DE_ZALIGSPREKENDEN.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0386-4_Zaligsprekingen.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'De Zaligsprekenden ' ],
[ '0387' ,'<a href=./0387_Zwervers.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zwervers' ], 
[ '0391' ,'<a href=./0391_WijZoekenU.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0391-4_WijZoekenU.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Wij zoeken U ' ],
[ '0392' ,'<a href=./0392_SoliDeoGloria.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0932-4_SoliDeoGloria.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Soli Deo Gloria ' ], 
[ '0393' ,'<a href=./0393_Mens_voor_de_mensen_zijn.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Mens voor de mensen zijn ' ], 
[ '0395' ,'<a href=./0395_ChristusOnzeHeerVerrees.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Christus onze Heer verrees' ], 
[ '0398' ,'<a href=./0398_ForTheBeautyOfTheEarth.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0398-4_ForTheBeautyOfTheEarth.pdf><img src="./Icon_PDF.png"width="20" height="20"></img> </a>','<a href=https://www.koorpartij-oefening.nl/oefenbestand-for-the-beauty-of-the-earth.html> <img src="./world-wide-web.png" width="20" height="20"></img> </a>' ,'', 'For the beauty of the earth (John Rutter)' ], 
[ '0402' ,'<a href=./0402_WeesHierAanwezig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wees hier aanwezig ' ], 
[ '0404' ,'<a href=./0404_DatUwWoordenInOnsBranden.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Dat uw woorden in ons branden' ], 
[ '0412' ,'<a href=./0412_WaarMensenElkaarDragen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Waar mensen elkaar dragen' ], 
[ '0415' ,'<a href=./0415_VredeVoorAlleMensen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede voor alle mensen' ], 
[ '0421' ,'<a href=./0421_JijDieBent.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jij die bent ' ], 
[ '0427' ,'<a href=./0427_Heer_WeesOnsGenadig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heer wees ons genadig ' ], 
[ '0428' ,'<a href=./0428_tIsGeboren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Het Is geboren' ], 
[ '0438' ,'<a href=./0438_LiedVanDeSchepping.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Lied van de schepping ' ], 
[ '0463' ,'<a href=./0463_40dagen40nachten.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0463-1_40dagen40nachten.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', '40 dagen 40 nachten' ],
[ '0464' ,'<a href=./0464_Litanie_van_alle_heiligen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Litanie van alle heiligen' ], 
[ '0471' ,'<a href=./0471_VertelHetAanDeMensen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vertel het aan de mensen ' ], 
[ '0475' ,'<a href=./0475_Maak_mij_een_werktuig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Maak mij een werktuig ' ], 
[ '0478' ,'<a href=./0478_Danklied.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Danklied' ], 
[ '0480' ,'<a href=./0480_Kyrie.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0480-4_Kyrie.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Kyrie' ],
[ '0486' ,'<a href=./0486_AlsRegenDieDeAardeDrenkt.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0486-4_AlsRegenDieDeAardeDrenkt.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Als regen die de aarde drenkt' ],
[ '0502' ,'<a href=./0502_AlWieDolendInHetDonker.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Al wie dolend in het donker ' ], 
[ '0503' ,'<a href=./0503-B_LaatMijNietLos.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laat mij niet los' ], 
[ '0506' ,'<a href=./0506_TheFirstNowel.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'The first nowell' ], 
[ '0513' ,'<a href=./0513_Broeders.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Broeders' ], 
[ '0515' ,'<a href=./0515_Bekering.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Bekering' ], 
[ '0518' ,'<a href=./0518_HetLiedOpDoodEnLeven.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0518-4_HetLiedOpDoodEnLeven.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Het lied op dood en leven' ],
[ '0537' ,'<a href=./0537_Heilig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0537-4_Heilig.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Heilig ' ],
[ '0540' ,'<a href=./0540_GebedOmVergeving.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gebed om vergeving ' ], 
[ '0541' ,'<a href=./0541_AdesteFideles.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Adeste fideles' ], 
[ '0544' ,'<a href=./0544_AveMaria.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ave Maria ' ], 
[ '0549' ,'<a href=./0549_LaudateOmnesGentes.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0549-4_LaudateOmnesGentes.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Laudate omnes gentes' ],
[ '0551' ,'<a href=./0551_GIJ_DIE_VOOR_ALLE_MENSEN.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gij die voor alle mensen ' ], 
[ '0587' ,'<a href=./0587_EerAanGodInDenHoge.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0587-4_EerAanGodInDenHoge.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Eer aan God in den hoge' ],
[ '0589' ,'<a href=./0589_GloryBeToGodTheFather.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Glory be to God the father' ], 
[ '0598' ,'<a href=./0598_HetLiedVanHetWater.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0598-4_HetLiedVanHetWater.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Het lied van het water' ],
[ '0608' ,'<a href=./0608_GezongenGebedsrefrein.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0608-4_GezongenGebedsrefrein.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Gezongen gebedsrefrein' ],
[ '0609' ,'<a href=./0609_Tussenzang_Laten_wij_zijn.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laten wij zijn als de levende stenen ' ], 
[ '0633' ,'<a href=./0633_HeerOntfermUOverOns.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heer ontferm U over ons' ], 
[ '0704' ,'<a href=./0704_LevenInOvervloed.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0704-4_LevenInOvervloed.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Leven in overvloed ' ],
[ '0710' ,'<a href=./0710_BroodOpTafel.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Brood op tafel' ], 
[ '0736' ,'<a href=./0736_AlsTussenLichtEnDonker.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Als tussen licht en donker' ], 
[ '0746' ,'<a href=./0746_DoorDeLiefdeLaatUWekken.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Door de liefde laat U wekken' ], 
[ '0769' ,'<a href=./0769_KwamVanGodswege.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kwam van godswege' ], 
[ '0779' ,'<a href=./0779_MensenVanOveralAangewaaid.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Mensen van overal aangewaaid' ], 
[ '0792' ,'<a href=./0792_Ga_dan_op_weg.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga dan op weg' ], 
[ '0793' ,'<a href=./0793_STA_OP_VOLK_VAN_GOD.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Sta op volk van god' ], 
[ '0795' ,'<a href=./0795_GaNaarDeStraten.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga naar de straten ' ], 
[ '0866' ,'<a href=./0866_Kyrie.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kyrie' ], 
[ '0872' ,'<a href=./0872_WijSpeurenInHetDuister.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wij speuren in het duister' ], 
[ '0876' ,'<a href=./0876_UwWoordIsEenLamp.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0876-1_UwWoordIsEenLamp.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Uw woord is een lamp' ],
[ '0877' ,'<a href=./0877_ZingNuDitLied.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0877-2_ZingNuDitLied.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Zing nu dit lied' ],
[ '0884' ,'<a href=./0884_Offerandelied.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Offerandelied' ], 
[ '0885' ,'<a href=./0885_TebePöem.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Tebe Pöem ' ], 
[ '0886' ,'<a href=./0886_SamenOpWegZoekendNaarLiefde.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Samen op weg zoekend naar liefde' ], 
[ '0917' ,'<a href=./0917_OldIrishBlessing.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Old Irish blessing ' ], 
[ '0988' ,'<a href=./0988_Sint_Antonius_van_Padua.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Sint Antonius van Padua' ], 
[ '0991' ,'<a href=./0991_GijDieVerrezenZijt.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gij die verrezen zijt ' ], 
[ '0992' ,'<a href=./0992_OnEcritSurLesMurs.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'On écrit sur les murs ' ], 
[ '1001' ,'<a href=./1001_VoorHetMooie.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Voor het mooie' ], 
[ '1105' ,'<a href=./1105_SchepperVanHetLeven.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Schepper van het leven' ], 
[ '1147' ,'<a href=./1147_EerAanGod.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Eer aan God' ], 
[ '1153' ,'<a href=./1153_LAUDATE_DOMINUM.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laudate Dominum ' ], 
[ '1182' ,'<a href=./1182_HetLiedVanDeKaarsen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Het lied van de kaarsen' ], 
[ '1271' ,'<a href=./1271_HoortMensenbroeders.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1271-4_HoortMensenbroeders.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Hoort mensenbroeders' ],
[ '1249' ,'<a href=./1249_TenHemelOpgestegen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ten hemel opgestegen' ], 
[ '1319' ,'<a href=./1319_HijDieGesprokenHeeft.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1319-2_HijDieGesprokenHeeft.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Hij die gesproken heeft' ],
[ '1346' ,'<a href=./1346_AlsJeIntLeven.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Als je in het leven' ], 
[ '1348' ,'<a href=./1348_BronInDeWoestijn.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1348-2_BronInDeWoestijn.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Bron in de woestijn' ],
[ '1424' ,'<a href=./1424_GloriaGloria.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gloria Gloria' ], 
[ '1444' ,'<a href=./1444_INeedTheeEveryHour.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'I need thee every hour' ], 
[ '1484' ,'<a href=./1484_OpdatUwDroom.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Opdat uw droom' ], 
[ '1486' ,'<a href=./1486_KomHeerJezus.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kom Heer Jezus' ], 
[ '1488' ,'<a href=./1488_AmbrosiaanseLofzang.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1488-7_AmbrosiaanseLofzang.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Ambrosiaanse lofzang' ],
[ '1494' ,'<a href=./1494_OveralMetJezus.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Overal met Jezus' ], 
[ '1507' ,'<a href=./1507_Heilig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heilig ' ], 
[ '1511' ,'<a href=./1511_HeerWeesMijnKracht.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1511-4_HeerWeesMijnKracht_inD.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Heer wees mijn kracht ' ],
[ '1602' ,'<a href=./1602_Wees_niet_bevreesd.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wees niet bevreesd ' ], 
[ '1606' ,'<a href=./1606_God_met_mij_op_alle_wegen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'God met mij op alle wegen' ], 
[ '1609' ,'<a href=./1609_Dank_U_Heer.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Dank u heer' ], 
[ '1610' ,'<a href=./1610_lofgezongen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'lofgezongen' ], 
[ '1612' ,'<a href=./1612_Vrede_van_God.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede van God' ], 
[ '1643' ,'<a href=./1643_Halleluja_GodSchenktOns.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1643-5_Halleluja_GodSchenktOnsDeToekomst.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Halleluja God schenkt ons' ],
[ '1655' ,'<a href=./1655_Het_lied_van_samen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Het lied van samen ' ], 
[ '1658' ,'<a href=./1658_HoorDeHerders.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Hoor de herders ' ], 
[ '1660' ,'<a href=./1660_Kerstzegen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kerstzegen' ], 
[ '1670',  ' ', ' ' , '<a href=https://www.youtube.com/watch?v=Kkz_14GR_D8> <img src="./world-wide-web.png" width="20" height="20"> </a>', '' , 'Jezus diep in de woestijn'       ],
[ '1702' ,'<a href=./1702_AlsInTBrood.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1702-4_AlsInTBrood.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Als in het brood' ],
[ '1703' ,'<a href=./1703_KijkVooruit.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kijk vooruit ' ], 
[ '1705' ,'<a href=./1705_IkZoekEenLand.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ik zoek een land' ], 
[ '1706' ,'<a href=./1706_GEBED_VAN_SINT-FRANCISCUS.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gebed van Sint-Franciscus' ], 
[ '1710' ,'<a href=./1710_MijnToeverlaat.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1710-4_MijnToeverlaat.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Mijn toeverlaat ' ], 
[ '1775' ,'<a href=./1775_TenHemelOpgevaren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ten hemel opgevaren' ], 
[ '1799' ,'<a href=./1799_Toon_ons_uw_Zoon.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1799-4_ToonOnsUwZoon.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Toon ons uw Zoon' ],
[ '1801' ,'<a href=./1801_Gelukkig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1801-4_Gelukkig.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Gelukkig' ],
[ '1802' ,'<a href=./1802_ElHimnoDeLaPaz(Chili).html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'El himno de la paz (Chili)' ], 
[ '1902' ,'<a href=./1902_TheRoadGoesEverOnAndOn.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'The road goes ever on and on' ], 
[ '1906' ,'<a href=./1906_Alleluia.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Alleluia' ], 
[ '1907' ,'<a href=./1907_AlsHetBroodDatWijDelen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Als het brood dat wij delen ' ], 
[ '1914' ,'<a href=./1914_JesusChristYouAreMyLife.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jesus Christ you are my life' ], 
[ '1917' ,'<a href=./1917_AdoramusTe.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Adoramus te' ],
[ '1946' ,'<a href=./1946_DoopOnsHeer.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Doop ons heer' ], 
[ '1949' ,'<a href=./1949_KyriëEleison.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1949-4_KyriëEleison.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Kyrië eleison' ],
[ '1951' ,'<a href=./1951_Heer_verhoor_ons.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heer verhoor ons' ], 
[ '1954' ,'<a href=./1954_GoedeVaderVanAlleVolken.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Goede vader van alle volken ' ], 
];


function createTable(dataFarde) {
  const [headings, ...rows] = dataFarde;
      
    return `
          <table>
            <thead>${getCells(headings, 'th')}</thead>
            <tbody>${rows.map(getRow).join('')}</tbody>
          </table>
    `;
}

document.body.insertAdjacentHTML('beforeend', createTable(dataFarde));
=======

let dataFarde = [
    ['nummer',  'coria '                                                                                                    , 'pdf'                                                                                                          , 'web'                                                                                                              , 'mp3'                                                                                      , 'titel'                           ],
    [  '0003',  '<a href=./0003_HijDieDeBlindenWeerLietZien.html><img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0003_4_HijDieDeBlindenWeerLietZien.pdf><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Hij die de blinden weer liet zien'       ],
    [  '0004',  '<a href=./0004_PelgrimsVanHoop.html>            <img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0004-4_PelgrimsVanHoop.pdf            ><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Pelgrims van hoop'                       ],
    [  '0025',  '<a href=./0025_Sanctus.html>                    <img src="./quaver.svg"  width="20" height="20"></img></a>', ''                                                                                                             , ''                                                                                                                 , ''                                                                                         , 'Sanctus'                                 ],
    [  '0035',  '<a href=./0035_KwaadEnZorgen.html>              <img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0035-2_KwaadEnZorgen.pdf              ><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Kwaad en zorgen'                         ],
    [  '0041',  '<a href=./0041_Pelgrimslied.html>               <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Pelgrimslied'                            ],
    [  '0043',  '<a href=./0043_GijSchreefMijnNaam.html>         <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Gij schreef mijn naam'                   ],
    [  '0059',  '<a href=./0059_LichtVanDeWereld.html>           <img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0059-4_LichtVanDeWereld.pdf           ><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Licht van de wereld'                     ],
    [  '0080',  '<a href=./0080_HeiligHeiligHeilig.html>         <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Heilig, heilig, heilig'                  ],
    [  '0082',  '<a href=./0082_BlijfMijNabij.html>              <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Blijf mij nabij'                         ],
    [  '0088',  '<a href=./0088_LooftDeHeer.html>                <img src="./quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Looft de Heer'                           ],
    [  '0089',  '<a href=./0089_SingJoyful.html>                 <img src="./quaver.svg"  width="20" height="20"></img></a>', '<a href=./SAK_0089-2_SingJoyfulPraise.pdf           ><img src="./Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Sing Joyful'                             ],
[ '0109' ,'<a href=./0109_GaMeeMetOns.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga mee met ons' ], 
[ '0112' ,'<a href=./0112_GloriaSeiDirGesungen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gloria sei dir gesungen' ], 
[ '0115' ,'<a href=./0115_HerdersHijIsGeboren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Herders Hij is geboren' ], 
[ '0121' ,'<a href=./0121_EerZijGod.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Eer zij God' ], 
[ '0126' ,'<a href=./0126_GodLeerdeOnsDeLiefde.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'God leerde ons de liefde ' ], 
[ '0140' ,'<a href=./0140_Da_pacem_domine.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Da pacem domine ' ],
[ '0169' ,'<a href=./0169_DonaLaPace.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0169-4_DonaLaPace.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Dona la pace ' ],
[ '0192' ,'<a href=./0192_BekommerdOmVrede.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Bekommerd om vrede ' ], 
[ '0197' ,'<a href=./0197_Alta_Trinità_beata.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Alta Trinità beata ' ], 
[ '0198' ,'<a href=./0198_DeSteppe.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'De steppe zal bloeien ' ], 
[ '0213' ,'<a href=./0213_GaJeAllenMetOnsMee.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga je allen met ons mee' ], 
[ '0220' ,'<a href=./0220_WaarJeWoontOpDezeWereld.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Waar je woont op deze wereld' ], 
[ '0237' ,'<a href=./0237_ZomaarEenDak.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zomaar een dak' ], 
[ '0244' ,'<a href=./0244_WakendUitzien.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wakend uitzien' ], 
[ '0247' ,'<a href=./0247_KindOnsGeboren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kind ons geboren' ], 
[ '0260' ,'<a href=./0260_DeGeestDesHeren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'De geest des heren ' ], 
[ '0266' ,'<a href=./0266_Here_der_Heren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Here der Heren' ], 
[ '0284' ,'<a href=./0284_JijHebtEenNaam.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jij hebt een naam' ], 
[ '0286' ,'<a href=./0286_GeprezenZijOnzeGod.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Geprezen zij onze God ' ], 
[ '0289' ,'<a href=./0289_IkZieDeHemelOpengaan.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0289-4_IkZieDeHemelOpengaan.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Ik zie de hemel opengaan ' ],
[ '0300' ,'<a href=./0300_LuisterHeer.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0300-4_LuisterHeer.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Luister Heer ' ],
[ '0301' ,'<a href=./0301_NieuweMensInOnsGeboren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0301-4_NieuweMensInOnsGeboren.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Nieuwe mens in ons geboren' ],
[ '0303' ,'<a href=./0303_LiedAanHetlicht.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Lied aan het licht ' ], 
[ '0309' ,'<a href=./0309_StadBovenWolken_HeerlijkVisioen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Stad boven wolken / Heerlijk visioen ' ], 
[ '0318' ,'<a href=./0318_Zing_met_mij_Halleluja.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zing met mij Halleluja' ], 
[ '0325' ,'<a href=./0325_VredeVoorJou.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede voor jou' ], 
[ '0337' ,'<a href=./0337_MariaDieZoude.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Maria die zoude naar Bethlehem gaan' ], 
[ '0338' ,'<a href=./0338_JouOntmoeten.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jou ontmoeten' ], 
[ '0341' ,'<a href=./0341_LichtOntlokenAanHetDonker.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0341-3_LichtOntlokenAanHetDonker_BZJ824.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Licht ontloken aan het donker' ],
[ '0344' ,'<a href=./0344_PrijzenWijDeHeer.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Prijzen wij de Heer' ],
[ '0345' ,'<a href=./0345_HereJezusOmUwWoord.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Here Jezus om uw woord' ], 
[ '0346' ,'<a href=./0346_Esengo.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Esengo ' ], 
[ '0347' ,'<a href=./0347_EensKomtDeDagWaarvanWijDromen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Eens komt de dag waarvan wij dromen' ], 
[ '0349' ,'<a href=./0349_LichtInOnzeOgen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Lichtin onze ogen' ], 
[ '0351' ,'<a href=./0351_Eer_aan_onze_God.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0351-4_EerAanOnzeGod.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Eer aan onze God' ],
[ '0355' ,'<a href=./0355_GegroetJijDieHierKomtOmLicht.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gegroet jij die hier komt om licht' ], 
[ '0359' ,'<a href=./0359_KleinPaaslied.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0359-4_KleinPaaslied.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Klein Paaslied' ],
[ '0361' ,'<a href=./0361_StemVanVuur.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0361-4_StemVanVuur.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Stem van vuur' ],
[ '0362' ,'<a href=./0362_OmdatHijLeeft.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Omdat hij leeft ' ],
[ '0363' ,'<a href=./0363_ZEGEN_VAN_SINT-FRANCISCUS.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Zegen van Sint-Franciscus' ],
[ '0369' ,'<a href=./0369_WijGelovenInHetLeven.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Wij geloven in het leven ' ],
[ '0373' ,'<a href=./0373_ZONNELIED_VAN_FRANCISCUS.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zonnelied van Franciscus ' ], 
[ '0376' ,'<a href=./0376_DonaNobisPacem.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Dona nobis pacem' ], 
[ '0377' ,'<a href=./0377_AllesWatUPrijzenKan.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Alles wat U prijzen kan (Großer Gott wit loben Dir)' ], 
[ '0381' ,'<a href=./0381_Thuma_Mina.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0381-4-ThumaMina.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Thuma Mina' ],
[ '0386' ,'<a href=./0386_DE_ZALIGSPREKENDEN.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0386-4_Zaligsprekingen.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'De Zaligsprekenden ' ],
[ '0387' ,'<a href=./0387_Zwervers.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zwervers' ], 
[ '0391' ,'<a href=./0391_WijZoekenU.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0391-4_WijZoekenU.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Wij zoeken U ' ],
[ '0392' ,'<a href=./0392_SoliDeoGloria.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0932-4_SoliDeoGloria.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Soli Deo Gloria ' ], 
[ '0393' ,'<a href=./0393_Mens_voor_de_mensen_zijn.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Mens voor de mensen zijn ' ], 
[ '0395' ,'<a href=./0395_ChristusOnzeHeerVerrees.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Christus onze Heer verrees' ], 
[ '0398' ,'<a href=./0398_ForTheBeautyOfTheEarth.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0398-4_ForTheBeautyOfTheEarth.pdf><img src="./Icon_PDF.png"width="20" height="20"></img> </a>','<a href=https://www.koorpartij-oefening.nl/oefenbestand-for-the-beauty-of-the-earth.html> <img src="./world-wide-web.png" width="20" height="20"></img> </a>' ,'', 'For the beauty of the earth (John Rutter)' ], 
[ '0402' ,'<a href=./0402_WeesHierAanwezig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wees hier aanwezig ' ], 
[ '0404' ,'<a href=./0404_DatUwWoordenInOnsBranden.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Dat uw woorden in ons branden' ], 
[ '0412' ,'<a href=./0412_WaarMensenElkaarDragen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Waar mensen elkaar dragen' ], 
[ '0415' ,'<a href=./0415_VredeVoorAlleMensen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede voor alle mensen' ], 
[ '0421' ,'<a href=./0421_JijDieBent.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jij die bent ' ], 
[ '0427' ,'<a href=./0427_Heer_WeesOnsGenadig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heer wees ons genadig ' ], 
[ '0428' ,'<a href=./0428_tIsGeboren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Het Is geboren' ], 
[ '0438' ,'<a href=./0438_LiedVanDeSchepping.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Lied van de schepping ' ], 
[ '0463' ,'<a href=./0463_40dagen40nachten.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0463-1_40dagen40nachten.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', '40 dagen 40 nachten' ],
[ '0464' ,'<a href=./0464_Litanie_van_alle_heiligen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Litanie van alle heiligen' ], 
[ '0471' ,'<a href=./0471_VertelHetAanDeMensen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vertel het aan de mensen ' ], 
[ '0475' ,'<a href=./0475_Maak_mij_een_werktuig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Maak mij een werktuig ' ], 
[ '0478' ,'<a href=./0478_Danklied.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Danklied' ], 
[ '0480' ,'<a href=./0480_Kyrie.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0480-4_Kyrie.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Kyrie' ],
[ '0486' ,'<a href=./0486_AlsRegenDieDeAardeDrenkt.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0486-4_AlsRegenDieDeAardeDrenkt.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Als regen die de aarde drenkt' ],
[ '0502' ,'<a href=./0502_AlWieDolendInHetDonker.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Al wie dolend in het donker ' ], 
[ '0503' ,'<a href=./0503-B_LaatMijNietLos.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laat mij niet los' ], 
[ '0506' ,'<a href=./0506_TheFirstNowel.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'The first nowell' ], 
[ '0513' ,'<a href=./0513_Broeders.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Broeders' ], 
[ '0515' ,'<a href=./0515_Bekering.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Bekering' ], 
[ '0518' ,'<a href=./0518_HetLiedOpDoodEnLeven.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0518-4_HetLiedOpDoodEnLeven.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Het lied op dood en leven' ],
[ '0537' ,'<a href=./0537_Heilig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_0537-4_Heilig.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Heilig ' ],
[ '0540' ,'<a href=./0540_GebedOmVergeving.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gebed om vergeving ' ], 
[ '0541' ,'<a href=./0541_AdesteFideles.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Adeste fideles' ], 
[ '0544' ,'<a href=./0544_AveMaria.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ave Maria ' ], 
[ '0549' ,'<a href=./0549_LaudateOmnesGentes.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0549-4_LaudateOmnesGentes.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Laudate omnes gentes' ],
[ '0551' ,'<a href=./0551_GIJ_DIE_VOOR_ALLE_MENSEN.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gij die voor alle mensen ' ], 
[ '0587' ,'<a href=./0587_EerAanGodInDenHoge.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0587-4_EerAanGodInDenHoge.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Eer aan God in den hoge' ],
[ '0589' ,'<a href=./0589_GloryBeToGodTheFather.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Glory be to God the father' ], 
[ '0598' ,'<a href=./0598_HetLiedVanHetWater.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0598-4_HetLiedVanHetWater.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Het lied van het water' ],
[ '0608' ,'<a href=./0608_GezongenGebedsrefrein.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0608-4_GezongenGebedsrefrein.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Gezongen gebedsrefrein' ],
[ '0609' ,'<a href=./0609_Tussenzang_Laten_wij_zijn.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laten wij zijn als de levende stenen ' ], 
[ '0633' ,'<a href=./0633_HeerOntfermUOverOns.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heer ontferm U over ons' ], 
[ '0704' ,'<a href=./0704_LevenInOvervloed.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0704-4_LevenInOvervloed.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Leven in overvloed ' ],
[ '0710' ,'<a href=./0710_BroodOpTafel.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Brood op tafel' ], 
[ '0736' ,'<a href=./0736_AlsTussenLichtEnDonker.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Als tussen licht en donker' ], 
[ '0746' ,'<a href=./0746_DoorDeLiefdeLaatUWekken.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Door de liefde laat U wekken' ], 
[ '0769' ,'<a href=./0769_KwamVanGodswege.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kwam van godswege' ], 
[ '0779' ,'<a href=./0779_MensenVanOveralAangewaaid.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Mensen van overal aangewaaid' ], 
[ '0792' ,'<a href=./0792_Ga_dan_op_weg.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga dan op weg' ], 
[ '0793' ,'<a href=./0793_STA_OP_VOLK_VAN_GOD.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Sta op volk van god' ], 
[ '0795' ,'<a href=./0795_GaNaarDeStraten.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga naar de straten ' ], 
[ '0866' ,'<a href=./0866_Kyrie.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kyrie' ], 
[ '0872' ,'<a href=./0872_WijSpeurenInHetDuister.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wij speuren in het duister' ], 
[ '0876' ,'<a href=./0876_UwWoordIsEenLamp.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0876-1_UwWoordIsEenLamp.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Uw woord is een lamp' ],
[ '0877' ,'<a href=./0877_ZingNuDitLied.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_0877-2_ZingNuDitLied.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Zing nu dit lied' ],
[ '0884' ,'<a href=./0884_Offerandelied.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Offerandelied' ], 
[ '0885' ,'<a href=./0885_TebePöem.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Tebe Pöem ' ], 
[ '0886' ,'<a href=./0886_SamenOpWegZoekendNaarLiefde.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Samen op weg zoekend naar liefde' ], 
[ '0916' ,'<a href=./0916_GeproefdGeleefdHerkend.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Geproefd, geleefd, herkend ' ], 
[ '0917' ,'<a href=./0917_OldIrishBlessing.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Old Irish blessing ' ], 
[ '0988' ,'<a href=./0988_Sint_Antonius_van_Padua.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Sint Antonius van Padua' ], 
[ '0991' ,'<a href=./0991_GijDieVerrezenZijt.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gij die verrezen zijt ' ], 
[ '0992' ,'<a href=./0992_OnEcritSurLesMurs.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'On écrit sur les murs ' ], 
[ '1001' ,'<a href=./1001_VoorHetMooie.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Voor het mooie' ], 
[ '1105' ,'<a href=./1105_SchepperVanHetLeven.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Schepper van het leven' ], 
[ '1147' ,'<a href=./1147_EerAanGod.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Eer aan God' ], 
[ '1153' ,'<a href=./1153_LAUDATE_DOMINUM.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laudate Dominum ' ], 
[ '1182' ,'<a href=./1182_HetLiedVanDeKaarsen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Het lied van de kaarsen' ], 
[ '1271' ,'<a href=./1271_HoortMensenbroeders.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1271-4_HoortMensenbroeders.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Hoort mensenbroeders' ],
[ '1249' ,'<a href=./1249_TenHemelOpgestegen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ten hemel opgestegen' ], 
[ '1319' ,'<a href=./1319_HijDieGesprokenHeeft.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1319-2_HijDieGesprokenHeeft.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Hij die gesproken heeft' ],
[ '1346' ,'<a href=./1346_AlsJeIntLeven.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Als je in het leven' ], 
[ '1348' ,'<a href=./1348_BronInDeWoestijn.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1348-2_BronInDeWoestijn.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Bron in de woestijn' ],
[ '1424' ,'<a href=./1424_GloriaGloria.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gloria Gloria' ], 
[ '1444' ,'<a href=./1444_INeedTheeEveryHour.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'I need thee every hour' ], 
[ '1484' ,'<a href=./1484_OpdatUwDroom.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Opdat uw droom' ], 
[ '1486' ,'<a href=./1486_KomHeerJezus.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kom Heer Jezus' ], 
[ '1488' ,'<a href=./1488_AmbrosiaanseLofzang.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1488-7_AmbrosiaanseLofzang.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Ambrosiaanse lofzang' ],
[ '1494' ,'<a href=./1494_OveralMetJezus.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Overal met Jezus' ], 
[ '1507' ,'<a href=./1507_Heilig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heilig ' ], 
[ '1511' ,'<a href=./1511_HeerWeesMijnKracht.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1511-4_HeerWeesMijnKracht_inD.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Heer wees mijn kracht ' ],
[ '1602' ,'<a href=./1602_Wees_niet_bevreesd.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wees niet bevreesd ' ], 
[ '1606' ,'<a href=./1606_God_met_mij_op_alle_wegen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'God met mij op alle wegen' ], 
[ '1609' ,'<a href=./1609_Dank_U_Heer.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Dank u heer' ], 
[ '1610' ,'<a href=./1610_lofgezongen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'lofgezongen' ], 
[ '1612' ,'<a href=./1612_Vrede_van_God.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede van God' ], 
[ '1643' ,'<a href=./1643_Halleluja_GodSchenktOns.html><img src="./quaver.svg"width="20" height="20"></img></a>','<a href=./SAK_1643-5_Halleluja_GodSchenktOnsDeToekomst.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Halleluja God schenkt ons' ],
[ '1655' ,'<a href=./1655_Het_lied_van_samen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Het lied van samen ' ], 
[ '1658' ,'<a href=./1658_HoorDeHerders.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Hoor de herders ' ], 
[ '1660' ,'<a href=./1660_Kerstzegen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kerstzegen' ], 
[ '1670',  ' ', ' ' , '<a href=https://www.youtube.com/watch?v=Kkz_14GR_D8> <img src="./world-wide-web.png" width="20" height="20"> </a>', '' , 'Jezus diep in de woestijn'       ],
[ '1702' ,'<a href=./1702_AlsInTBrood.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1702-4_AlsInTBrood.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Als in het brood' ],
[ '1703' ,'<a href=./1703_KijkVooruit.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kijk vooruit ' ], 
[ '1705' ,'<a href=./1705_IkZoekEenLand.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ik zoek een land' ], 
[ '1706' ,'<a href=./1706_GEBED_VAN_SINT-FRANCISCUS.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gebed van Sint-Franciscus' ], 
[ '1710' ,'<a href=./1710_MijnToeverlaat.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1710-4_MijnToeverlaat.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Mijn toeverlaat ' ], 
[ '1775' ,'<a href=./1775_TenHemelOpgevaren.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ten hemel opgevaren' ], 
[ '1799' ,'<a href=./1799_Toon_ons_uw_Zoon.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1799-4_ToonOnsUwZoon.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Toon ons uw Zoon' ],
[ '1801' ,'<a href=./1801_Gelukkig.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1801-4_Gelukkig.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Gelukkig' ],
[ '1802' ,'<a href=./1802_ElHimnoDeLaPaz(Chili).html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'El himno de la paz (Chili)' ], 
[ '1902' ,'<a href=./1902_TheRoadGoesEverOnAndOn.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'The road goes ever on and on' ], 
[ '1906' ,'<a href=./1906_Alleluia.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Alleluia' ], 
[ '1907' ,'<a href=./1907_AlsHetBroodDatWijDelen.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Als het brood dat wij delen ' ], 
[ '1914' ,'<a href=./1914_JesusChristYouAreMyLife.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jesus Christ you are my life' ], 
[ '1917' ,'<a href=./1917_AdoramusTe.html><img src="./quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Adoramus te' ],
[ '1946' ,'<a href=./1946_DoopOnsHeer.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Doop ons heer' ], 
[ '1949' ,'<a href=./1949_KyriëEleison.html><img src="./quaver.svg"width="20" height="20"></img></a>',' <a href=./SAK_1949-4_KyriëEleison.pdf><img src="./Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Kyrië eleison' ],
[ '1951' ,'<a href=./1951_Heer_verhoor_ons.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heer verhoor ons' ], 
[ '1954' ,'<a href=./1954_GoedeVaderVanAlleVolken.html><img src="./quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Goede vader van alle volken ' ], 
];


function createTable(dataFarde) {
  const [headings, ...rows] = dataFarde;
      
    return `
          <table>
            <thead>${getCells(headings, 'th')}</thead>
            <tbody>${rows.map(getRow).join('')}</tbody>
          </table>
    `;
}

document.body.insertAdjacentHTML('beforeend', createTable(dataFarde));
>>>>>>> 51a61b4af502c8f6ec8acac1917e37e617445e2b
