let dataFarde0000 = [
['nummer',  'coria '                                                                                                    , 'pdf'                                                                                                          , 'web'                                                                                                              , 'mp3'                                                                                      , 'titel'                           ],
[ '0001' ,'<a href=coria/0001_WieGodsRechteWegenGaat.html>     <img src="src/quaver.svg"  width="20" height="20"></img></a>', '<a href=pdf/SAK_0001-3_WieGodsRechteWegenGaat.pdf>     <img src="src/Icon_PDF.png"  width="20" height="20"></a>'  , '<a href=https://www.youtube.com/watch?v=v_ryzBavlQA> <img src="src/world-wide-web.png" width="20" height="20"> </a>'   , ''                                                                                         , 'Wie Gods rechte wegen gaat'       ],
[ '0003' ,'<a href=coria/0003_HijDieDeBlindenWeerLietZien.html><img src="src/quaver.svg"  width="20" height="20"></img></a>', '<a href=pdf/SAK_0003_4_HijDieDeBlindenWeerLietZien.pdf><img src="src/Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Hij die de blinden weer liet zien'       ],
[ '0004' ,'<a href=coria/0005_LaatUwLiefde.html>               <img src="src/quaver.svg"  width="20" height="20"></img></a>', ''                                                                                                                 , ''                                                                                                                 , ''                                                                                         , 'Laat Uw Liefde'                       ],
[ '0005' ,'<a href=coria/0004_PelgrimsVanHoop.html>            <img src="src/quaver.svg"  width="20" height="20"></img></a>', '<a href=pdf/SAK_0004-4_PelgrimsVanHoop.pdf            ><img src="src/Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Pelgrims van hoop'                       ],
[ '0025' ,'<a href=coria/0025_Sanctus.html>                    <img src="src/quaver.svg"  width="20" height="20"></img></a>', ''                                                                                                                 , ''                                                                                                                 , ''                                                                                         , 'Sanctus'                                 ],
[ '0035' ,'<a href=coria/0035_KwaadEnZorgen.html>              <img src="src/quaver.svg"  width="20" height="20"></img></a>', '<a href=pdf/SAK_0035-2_KwaadEnZorgen.pdf              ><img src="src/Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Kwaad en zorgen'                         ],
[ '0041' ,'<a href=coria/0041_Pelgrimslied.html>               <img src="src/quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Pelgrimslied'                            ],
[ '0043' ,'<a href=coria/0043_GijSchreefMijnNaam.html>         <img src="src/quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Gij schreef mijn naam'                   ],
[ '0059' ,'<a href=coria/0059_LichtVanDeWereld.html>           <img src="src/quaver.svg"  width="20" height="20"></img></a>', '<a href=pdf/SAK_0059-4_LichtVanDeWereld.pdf           ><img src="src/Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Licht van de wereld'                     ],
[ '0080' ,'<a href=coria/0080_HeiligHeiligHeilig.html>         <img src="src/quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Heilig, heilig, heilig'                  ],
[ '0082' ,'<a href=coria/0082_BlijfMijNabij.html>              <img src="src/quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Blijf mij nabij'                         ],
[ '0088' ,'<a href=coria/0088_LooftDeHeer.html>                <img src="src/quaver.svg"  width="20" height="20"></img></a>', '                                                                                                           '  , ''                                                                                                                 , ''                                                                                         , 'Looft de Heer'                           ],
[ '0089' ,'<a href=coria/0089_SingJoyful.html>                 <img src="src/quaver.svg"  width="20" height="20"></img></a>', '<a href=pdf/SAK_0089-2_SingJoyfulPraise.pdf           ><img src="src/Icon_PDF.png"  width="20" height="20"></a>'  , ''                                                                                                                 , ''                                                                                         , 'Sing Joyful'                             ],
[ '    ' ,'                                                                                                          ',' ','' ,'', '                           ' ] 
];


function createTable(dataFarde0000) {
  const [headings, ...rows] = dataFarde0000;
      
    return `
          <table>
            <thead>${getCells(headings, 'th')}</thead>
            <tbody>${rows.map(getRow).join('')}</tbody>
          </table>
    `;
}

document.body.insertAdjacentHTML('beforeend', createTable(dataFarde0000));
