let dataFarde0300 = [
['nummer',  'coria '                                                                                                    , 'pdf'                                                                                                          , 'web'                                                                                                              , 'mp3'                                                                                      , 'titel'                           ],
[ '0300' ,'<a href=coria/0300_LuisterHeer.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0300-4_LuisterHeer.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Luister Heer ' ],
[ '0301' ,'<a href=coria/0301_NieuweMensInOnsGeboren.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0301-4_NieuweMensInOnsGeboren.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Nieuwe mens in ons geboren' ],
[ '0303' ,'<a href=coria/0303_LiedAanHetlicht.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Lied aan het licht ' ], 
[ '0309' ,'<a href=coria/0309_StadBovenWolken_HeerlijkVisioen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Stad boven wolken / Heerlijk visioen ' ], 
[ '0318' ,'<a href=coria/0318_Zing_met_mij_Halleluja.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zing met mij Halleluja' ], 
[ '0325' ,'<a href=coria/0325_VredeVoorJou.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede voor jou' ], 
[ '0337' ,'<a href=coria/0337_MariaDieZoude.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Maria die zoude naar Bethlehem gaan' ], 
[ '0338' ,'<a href=coria/0338_JouOntmoeten.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jou ontmoeten' ], 
[ '0341' ,'<a href=coria/0341_LichtOntlokenAanHetDonker.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0341-3_LichtOntlokenAanHetDonker_BZJ824.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Licht ontloken aan het donker' ],
[ '0342' ,'<a href=coria/0342_OmEenMensTeZijnOpAarde.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Om een mens te zijn' ],
[ '0344' ,'<a href=coria/0344_PrijzenWijDeHeer.html><img src="src/quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Prijzen wij de Heer' ],
[ '0345' ,'<a href=coria/0345_HereJezusOmUwWoord.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Here Jezus om uw woord' ], 
[ '0346' ,'<a href=coria/0346_Esengo.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Esengo ' ], 
[ '0347' ,'<a href=coria/0347_EensKomtDeDagWaarvanWijDromen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Eens komt de dag waarvan wij dromen' ], 
[ '0349' ,'<a href=coria/0349_LichtInOnzeOgen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Lichtin onze ogen' ], 
[ '0351' ,'<a href=coria/0351_Eer_aan_onze_God.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0351-4_EerAanOnzeGod.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Eer aan onze God' ],
[ '0355' ,'<a href=coria/0355_GegroetJijDieHierKomtOmLicht.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gegroet jij die hier komt om licht' ], 
[ '0359' ,'<a href=coria/0359_KleinPaaslied.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0359-4_KleinPaaslied.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Klein Paaslied' ],
[ '0361' ,'<a href=coria/0361_StemVanVuur.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0361-4_StemVanVuur.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Stem van vuur' ],
[ '0362' ,'<a href=coria/0362_OmdatHijLeeft.html><img src="src/quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Omdat hij leeft ' ],
[ '0363' ,'<a href=coria/0363_ZEGEN_VAN_SINT-FRANCISCUS.html><img src="src/quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Zegen van Sint-Franciscus' ],
[ '0369' ,'<a href=coria/0369_WijGelovenInHetLeven.html><img src="src/quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Wij geloven in het leven ' ],
[ '0373' ,'<a href=coria/0373_ZONNELIED_VAN_FRANCISCUS.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zonnelied van Franciscus ' ], 
[ '0376' ,'<a href=coria/0376_DonaNobisPacem.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Dona nobis pacem' ], 
[ '0377' ,'<a href=coria/0377_AllesWatUPrijzenKan.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Alles wat U prijzen kan (Großer Gott wit loben Dir)' ], 
[ '0381' ,'<a href=coria/0381_Thuma_Mina.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0381-4-ThumaMina.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Thuma Mina' ],
[ '0384' ,'<a href=coria/0384_Kyrie.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kyrie (Mokonzi' ], 
[ '0385' ,'<a href=coria/0385_TelUwHerinneringen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0385-4_TelUwHerinneringen.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Tel uw herinneringen' ],
[ '0386' ,'<a href=coria/0386_DE_ZALIGSPREKENDEN.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0386-4_Zaligsprekingen.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'De Zaligsprekenden ' ],
[ '0387' ,'<a href=coria/0387_Zwervers.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Zwervers' ], 
[ '0391' ,'<a href=coria/0391_WijZoekenU.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0391-4_WijZoekenU.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Wij zoeken U ' ],
[ '0392' ,'<a href=coria/0392_SoliDeoGloria.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0932-4_SoliDeoGloria.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Soli Deo Gloria ' ], 
[ '0393' ,'<a href=coria/0393_Mens_voor_de_mensen_zijn.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Mens voor de mensen zijn ' ], 
[ '0394' ,'<a href=coria/0394_BlijfNietStaren.html> <img src="src/quaver.svg"  width="20" height="20"></img></a>', ''  , '' , '' , 'Blijf niet staren' ],
[ '0395' ,'<a href=coria/0395_ChristusOnzeHeerVerrees.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Christus onze Heer verrees' ], 
[ '0398' ,'<a href=coria/0398_ForTheBeautyOfTheEarth.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0398-4_ForTheBeautyOfTheEarth.pdf><img src="src/Icon_PDF.png"width="20" height="20"></img> </a>','<a href=https://www.koorpartij-oefening.nl/oefenbestand-for-the-beauty-of-the-earth.html> <img src="src/world-wide-web.png" width="20" height="20"></img> </a>' ,'', 'For the beauty of the earth (John Rutter)' ], 
[ '0402' ,'<a href=coria/0402_WeesHierAanwezig.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wees hier aanwezig ' ], 
[ '0404' ,'<a href=coria/0404_DatUwWoordenInOnsBranden.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Dat uw woorden in ons branden' ], 
[ '0412' ,'<a href=coria/0412_WaarMensenElkaarDragen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Waar mensen elkaar dragen' ], 
[ '0415' ,'<a href=coria/0415_VredeVoorAlleMensen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede voor alle mensen' ], 
[ '0421' ,'<a href=coria/0421_JijDieBent.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jij die bent ' ], 
[ '0422' ,'<a href=coria/0422_BlijfNietStaan.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Blijf niet staan' ],   
[ '0424' ,'<a href=coria/0424_AdventIsDromen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Advent is dromen' ],   
[ '0426' ,'<a href=coria/0426_WanneerZalDeMensTochKomen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wanneer zal de mens toch komen' ],   
[ '0427' ,'<a href=coria/0427_Heer_WeesOnsGenadig.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heer wees ons genadig ' ], 
[ '0428' ,'<a href=coria/0428_tIsGeboren.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Het Is geboren' ], 
[ '0438' ,'<a href=coria/0438_LiedVanDeSchepping.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Lied van de schepping ' ], 
[ '0463' ,'<a href=coria/0463_40dagen40nachten.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0463-1_40dagen40nachten.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', '40 dagen 40 nachten' ],
[ '0464' ,'<a href=coria/0464_Litanie_van_alle_heiligen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Litanie van alle heiligen' ], 
[ '0471' ,'<a href=coria/0471_VertelHetAanDeMensen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vertel het aan de mensen ' ], 
[ '0475' ,'<a href=coria/0475_Maak_mij_een_werktuig.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Maak mij een werktuig ' ], 
[ '0478' ,'<a href=coria/0478_Danklied.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Danklied' ], 
[ '0480' ,'<a href=coria/0480_Kyrie.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0480-4_Kyrie.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Kyrie' ],
[ '0486' ,'<a href=coria/0486_AlsRegenDieDeAardeDrenkt.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0486-4_AlsRegenDieDeAardeDrenkt.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Als regen die de aarde drenkt' ],
[ '0502' ,'<a href=coria/0502_AlWieDolendInHetDonker.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Al wie dolend in het donker ' ], 
[ '0503' ,'<a href=coria/0503-B_LaatMijNietLos.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laat mij niet los' ], 
[ '0506' ,'<a href=coria/0506_TheFirstNowel.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'The first nowell' ], 
[ '0513' ,'<a href=coria/0513_Broeders.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Broeders' ], 
[ '0515' ,'<a href=coria/0515_Bekering.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Bekering' ], 
[ '0518' ,'<a href=coria/0518_HetLiedOpDoodEnLeven.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0518-4_HetLiedOpDoodEnLeven.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Het lied op dood en leven' ],
[ '0537' ,'<a href=coria/0537_Heilig.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_0537-4_Heilig.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Heilig ' ],
[ '0539' ,'<a href=coria/0539_Heilig.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heilig ' ],
[ '0540' ,'<a href=coria/0540_GebedOmVergeving.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gebed om vergeving ' ], 
[ '0541' ,'<a href=coria/0541_AdesteFideles.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Adeste fideles' ], 
[ '0544' ,'<a href=coria/0544_AveMaria.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ave Maria ' ], 
[ '0549' ,'<a href=coria/0549_LaudateOmnesGentes.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0549-4_LaudateOmnesGentes.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Laudate omnes gentes' ],
[ '0551' ,'<a href=coria/0551_GIJ_DIE_VOOR_ALLE_MENSEN.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gij die voor alle mensen ' ], 
[ '0560' ,'<a href=coria/0560_AlHeeftHijOnsVerlaten.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Al heeft Hij ons verlaten (ZJ 412) ' ], 
[ '0587' ,'<a href=coria/0587_EerAanGodInDenHoge.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0587-4_EerAanGodInDenHoge.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Eer aan God in den hoge' ],
[ '0589' ,'<a href=coria/0589_GloryBeToGodTheFather.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Glory be to God the father' ], 
[ '0598' ,'<a href=coria/0598_HetLiedVanHetWater.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0598-4_HetLiedVanHetWater.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Het lied van het water' ],
[ '0608' ,'<a href=coria/0608_GezongenGebedsrefrein.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0608-4_GezongenGebedsrefrein.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Gezongen gebedsrefrein' ],
[ '0609' ,'<a href=coria/0609_Tussenzang_Laten_wij_zijn.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laten wij zijn als de levende stenen ' ], 
[ '0633' ,'<a href=coria/0633_HeerOntfermUOverOns.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heer ontferm U over ons' ], 
[ '0690' ,'<a href=coria/0690_VredeVoorIedereen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede voor iedereen' ], 
[ '0704' ,'<a href=coria/0704_LevenInOvervloed.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0704-4_LevenInOvervloed.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Leven in overvloed ' ],
[ '0710' ,'<a href=coria/0710_BroodOpTafel.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Brood op tafel' ], 
[ '0731' ,'<a href=coria/0731_ZingVoorDeHeer.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0731-3_ZingVoorDeHeer.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Zing voor de Heer' ], 
[ '0736' ,'<a href=coria/0736_AlsTussenLichtEnDonker.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Als tussen licht en donker' ], 
[ '0746' ,'<a href=coria/0746_DoorDeLiefdeLaatUWekken.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Door de liefde laat U wekken' ], 
[ '0769' ,'<a href=coria/0769_KwamVanGodswege.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kwam van godswege' ], 
[ '0779' ,'<a href=coria/0779_MensenVanOveralAangewaaid.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Mensen van overal aangewaaid' ], 
[ '0792' ,'<a href=coria/0792_Ga_dan_op_weg.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga dan op weg' ], 
[ '0793' ,'<a href=coria/0793_STA_OP_VOLK_VAN_GOD.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Sta op volk van god' ], 
[ '0795' ,'<a href=coria/0795_GaNaarDeStraten.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ga naar de straten ' ], 
[ '0865' ,'<a href=coria/0865_HebDank.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heb dank' ], 
[ '0866' ,'<a href=coria/0866_Kyrie.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kyrie' ], 
[ '0872' ,'<a href=coria/0872_WijSpeurenInHetDuister.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wij speuren in het duister' ], 
[ '0876' ,'<a href=coria/0876_UwWoordIsEenLamp.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0876-1_UwWoordIsEenLamp.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Uw woord is een lamp' ],
[ '0877' ,'<a href=coria/0877_ZingNuDitLied.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_0877-2_ZingNuDitLied.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Zing nu dit lied' ],
[ '0884' ,'<a href=coria/0884_Offerandelied.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Offerandelied' ], 
[ '0885' ,'<a href=coria/0885_TebePöem.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Tebe Pöem ' ], 
[ '0886' ,'<a href=coria/0886_SamenOpWegZoekendNaarLiefde.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Samen op weg zoekend naar liefde' ], 
[ '0916' ,'<a href=coria/0916_GeproefdGeleefdHerkend.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Geproefd, geleefd, herkend ' ], 
[ '0917' ,'<a href=coria/0917_OldIrishBlessing.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Old Irish blessing ' ], 
[ '0988' ,'<a href=coria/0988_Sint_Antonius_van_Padua.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Sint Antonius van Padua' ], 
[ '0991' ,'<a href=coria/0991_GijDieVerrezenZijt.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gij die verrezen zijt ' ], 
[ '0992' ,'<a href=coria/0992_OnEcritSurLesMurs.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'On écrit sur les murs ' ], 
[ '1001' ,'<a href=coria/1001_VoorHetMooie.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Voor het mooie' ], 
[ '1105' ,'<a href=coria/1105_SchepperVanHetLeven.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Schepper van het leven' ], 
[ '1107' ,'<a href=coria/1107_GodZalURedden.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'God zal u redden' ], 
[ '1147' ,'<a href=coria/1147_EerAanGod.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Eer aan God' ], 
[ '1153' ,'<a href=coria/1153_LAUDATE_DOMINUM.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laudate Dominum ' ], 
[ '1182' ,'<a href=coria/1182_HetLiedVanDeKaarsen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Het lied van de kaarsen' ], 
[ '1256' ,'<a href=coria/1256_GeenHerdersDieWaken.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_1256-4_GeenHerdersDieWaken.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'De herdertjes lagen bij nachte' ],
[ '1271' ,'<a href=coria/1271_HoortMensenbroeders.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_1271-4_HoortMensenbroeders.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Hoort mensenbroeders' ],
[ '1249' ,'<a href=coria/1249_TenHemelOpgestegen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ten hemel opgestegen' ], 
[ '1319' ,'<a href=coria/1319_HijDieGesprokenHeeft.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_1319-2_HijDieGesprokenHeeft.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Hij die gesproken heeft' ],
[ '1346' ,'<a href=coria/1346_AlsJeIntLeven.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Als je in het leven' ], 
[ '1348' ,'<a href=coria/1348_BronInDeWoestijn.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_1348-2_BronInDeWoestijn.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Bron in de woestijn' ],
[ '1424' ,'<a href=coria/1424_GloriaGloria.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gloria Gloria' ], 
[ '1444' ,'<a href=coria/1444_INeedTheeEveryHour.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'I need thee every hour' ], 
[ '1484' ,'<a href=coria/1484_OpdatUwDroom.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Opdat uw droom' ], 
[ '1485' ,'<a href=coria/1485_KomLuisterNaarMijnWoorden.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kom Luister naar mijn woorden' ], 
[ '1486' ,'<a href=coria/1486_KomHeerJezus.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kom Heer Jezus' ], 
[ '1488' ,'<a href=coria/1488_AmbrosiaanseLofzang.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_1488-7_AmbrosiaanseLofzang.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Ambrosiaanse lofzang' ],
[ '1494' ,'<a href=coria/1494_OveralMetJezus.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Overal met Jezus' ], 
[ '1502' ,'<a href=coria/1502_LaatZoJeLichtMaarSchijnen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Laat zo je licht maar schijnen' ], 
[ '1507' ,'<a href=coria/1507_Heilig.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heilig ' ], 
[ '1511' ,'<a href=coria/1511_HeerWeesMijnKracht.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_1511-4_HeerWeesMijnKracht_inD.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Heer wees mijn kracht ' ],
[ '1577' ,'<a href=coria/1577_EffenDeWeg.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Effen de weg' ], 
[ '1602' ,'<a href=coria/1602_Wees_niet_bevreesd.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Wees niet bevreesd ' ], 
[ '1606' ,'<a href=coria/1606_God_met_mij_op_alle_wegen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'God met mij op alle wegen' ], 
[ '1609' ,'<a href=coria/1609_Dank_U_Heer.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Dank u heer' ], 
[ '1610' ,'<a href=coria/1610_lofgezongen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'lofgezongen' ], 
[ '1612' ,'<a href=coria/1612_Vrede_van_God.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Vrede van God' ], 
[ '1643' ,'<a href=coria/1643_Halleluja_GodSchenktOns.html><img src="src/quaver.svg"width="20" height="20"></img></a>','<a href=pdf/SAK_1643-5_Halleluja_GodSchenktOnsDeToekomst.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Halleluja God schenkt ons' ],
[ '1653' ,'<a href=coria/1653_AlleluiaBereidDeWegDesHeren.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Alleluia Bereid de weg des Heren' ], 
[ '1655' ,'<a href=coria/1655_Het_lied_van_samen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Het lied van samen ' ], 
[ '1658' ,'<a href=coria/1658_HoorDeHerders.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Hoor de herders ' ], 
[ '1660' ,'<a href=coria/1660_Kerstzegen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kerstzegen' ], 
[ '1670', ' ', ' ' , '<a href=https://www.youtube.com/watch?v=Kkz_14GR_D8> <img src="src/world-wide-web.png" width="20" height="20"> </a>', '' , 'Jezus diep in de woestijn'       ],
[ '1702' ,'<a href=coria/1702_AlsInTBrood.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_1702-4_AlsInTBrood.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Als in het brood' ],
[ '1703' ,'<a href=coria/1703_KijkVooruit.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Kijk vooruit ' ], 
[ '1705' ,'<a href=coria/1705_IkZoekEenLand.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ik zoek een land' ], 
[ '1706' ,'<a href=coria/1706_GEBED_VAN_SINT-FRANCISCUS.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Gebed van Sint-Franciscus' ], 
[ '1710' ,'<a href=coria/1710_MijnToeverlaat.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_1710-4_MijnToeverlaat.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Mijn toeverlaat ' ], 
[ '1775' ,'<a href=coria/1775_TenHemelOpgevaren.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Ten hemel opgevaren' ], 
[ '1799' ,'<a href=coria/1799_Toon_ons_uw_Zoon.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_1799-4_ToonOnsUwZoon.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Toon ons uw Zoon' ],
[ '1801' ,'<a href=coria/1801_Gelukkig.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_1801-4_Gelukkig.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Gelukkig' ],
[ '1802' ,'<a href=coria/1802_ElHimnoDeLaPaz(Chili).html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'El himno de la paz (Chili)' ], 
[ '1902' ,'<a href=coria/1902_TheRoadGoesEverOnAndOn.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'The road goes ever on and on' ], 
[ '1906' ,'<a href=coria/1906_Alleluia.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Alleluia' ], 
[ '1907' ,'<a href=coria/1907_AlsHetBroodDatWijDelen.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Als het brood dat wij delen ' ], 
[ '1914' ,'<a href=coria/1914_JesusChristYouAreMyLife.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Jesus Christ you are my life' ], 
[ '1917' ,'<a href=coria/1917_AdoramusTe.html><img src="src/quaver.svg"width="20" height="20"></img></a>','','' ,'', 'Adoramus te' ],
[ '1946' ,'<a href=coria/1946_DoopOnsHeer.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Doop ons heer' ], 
[ '1949' ,'<a href=coria/1949_KyriëEleison.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' <a href=pdf/SAK_1949-4_KyriëEleison.pdf><img src="src/Icon_PDF.png"width="20" height="20"></a>','' ,'', 'Kyrië eleison' ],
[ '1951' ,'<a href=coria/1951_Heer_verhoor_ons.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Heer verhoor ons' ], 
[ '1954' ,'<a href=coria/1954_GoedeVaderVanAlleVolken.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Goede vader van alle volken ' ], 
[ '1962' ,'<a href=coria/1962_AdventDatIs.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Advent dat is' ], 
[ '1963' ,'<a href=coria/1963_FluisterDanDatJeGelooft.html><img src="src/quaver.svg"width="20" height="20"></img></a>',' ','' ,'', 'Fluister dan dat je gelooft' ],
[ '    ' ,'                                                                                                          ',' ','' ,'', '                           ' ] 
];


function createTable(dataFarde0300) {
  const [headings, ...rows] = dataFarde0300;
      
    return `
          <table>
            <thead>${getCells(headings, 'th')}</thead>
            <tbody>${rows.map(getRow).join('')}</tbody>
          </table>
    `;
}

document.body.insertAdjacentHTML('beforeend', createTable(dataFarde0300));
