let dataMP3Peter500 = [
    ['nummer',  'mp3' , 'titel' ],
    ['ZJ_501', '<a href=MP3_Peter/ZJ_501-Nu_looft_en_prijst_mijn_ziel_de_Heer.mp3>          <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_501-Nu_looft_en_prijst_mijn_ziel_de_Heer'                  ],
    ['ZJ_502', '<a href=MP3_Peter/ZJ_502-Verkondig_alle_mensen.mp3>                         <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_502-Verkondig_alle_mensen'                                 ],
    ['ZJ_503', '<a href=MP3_Peter/ZJ_503-Zingt_een_nieuw_lied_voor_de_Heer.mp3>             <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_503-Zingt_een_nieuw_lied_voor_de_Heer'                     ],
    ['ZJ_504', '<a href=MP3_Peter/ZJ_504-Wanneer_ik_door_de_velden_ga.mp3>                  <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_504-Wanneer_ik_door_de_velden_ga'                          ],
    ['ZJ_505', '<a href=MP3_Peter/ZJ_505-Zoals_een_hert_verlangt.mp3>                       <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_505-Zoals_een_hert_verlangt'                               ],
    ['ZJ_506', '<a href=MP3_Peter/ZJ_506-Mijn_Herder_zijt_Gij.mp3>                          <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_506-Mijn_Herder_zijt_Gij'                                  ],
    ['ZJ_507', '<a href=MP3_Peter/ZJ_507-Gij_zijt_een_bron.mp3>                             <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_507-Gij_zijt_een_bron'                                     ],
    ['ZJ_508', '<a href=MP3_Peter/ZJ_508-Die_rechtens_God_gelijk.mp3>                       <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_508-Die_rechtens_God_gelijk'                               ],
    ['ZJ_509', '<a href=MP3_Peter/ZJ_509-Mens_voor_de_mensen.mp3>                           <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_509-Mens_voor_de_mensen'                                   ],
    ['ZJ_511', '<a href=MP3_Peter/ZJ_511-De_Heer_is_Koning.mp3>                             <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_511-De_Heer_is_Koning'                                     ],
    ['ZJ_512', '<a href=MP3_Peter/ZJ_512-Eert_God_die_onze_Vader_is.mp3>                    <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_512-Eert_God_die_onze_Vader_is'                            ],
    ['ZJ_514', '<a href=MP3_Peter/ZJ_514-Zolang_er_mensen_zijn_op_aarde.mp3>                <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_514-Zolang_er_mensen_zijn_op_aarde'                        ],
    ['ZJ_516', '<a href=MP3_Peter/ZJ_516-Geef_vrede_Heer_geef_vrede.mp3>                    <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_516-Geef_vrede_Heer_geef_vrede'                            ],
    ['ZJ_518', '<a href=MP3_Peter/ZJ_518-Laat_ieder_s_Heren_goedheid_prijzen.mp3>           <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_518-Laat_ieder_s_Heren_goedheid_prijzen'                   ],
    ['ZJ_519', '<a href=MP3_Peter/ZJ_519-Zingt_een_nieuw_lied_voor_God_de_Here.mp3>         <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_519-Zingt_een_nieuw_lied_voor_God_de_Here'                 ],
    ['ZJ_520', '<a href=MP3_Peter/ZJ_520-Heer_onze_Heer_hoe_heerlijk_en_verheven.mp3>       <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_520-Heer_onze_Heer_hoe_heerlijk_en_verheven'               ],
    ['ZJ_521', '<a href=MP3_Peter/ZJ_521-De_Heer_richt_op_zijn_berg_een_maaltijd_aan.mp3>   <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_521-De_Heer_richt_op_zijn_berg_een_maaltijd_aan'           ],
    ['ZJ_522', '<a href=MP3_Peter/ZJ_522-Heer_laat_mij_voor_uw_altaar_komen.mp3>            <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_522-Heer_laat_mij_voor_uw_altaar_komen'                    ],
    ['ZJ_522', '<a href=MP3_Peter/ZJ_522-Heer_laat_mij_voor_uw_altaar_komen_-_bis.mp3>      <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_522-Heer_laat_mij_voor_uw_altaar_komen_-_bis'              ],
    ['ZJ_523', '<a href=MP3_Peter/ZJ_523-O_goddelijk_alvermogen.mp3>                        <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_523-O_goddelijk_alvermogen'                                ],
    ['ZJ_524', '<a href=MP3_Peter/ZJ_524-Samen_op_de_aarde.mp3>                             <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_524-Samen_op_de_aarde'                                     ],
    ['ZJ_525', '<a href=MP3_Peter/ZJ_525-God_zij_geloofd_om_Kanaän.mp3>                     <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_525-God_zij_geloofd_om_Kanaän'                             ],
    ['ZJ_526', '<a href=MP3_Peter/ZJ_526-Al_wat_er_nodig_is.mp3>                            <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_526-Al_wat_er_nodig_is'                                    ],
    ['ZJ_527', '<a href=MP3_Peter/ZJ_527-Bekleedt_u_met_de_nieuwe_mens.mp3>                 <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_527-Bekleedt_u_met_de_nieuwe_mens'                         ],
    ['ZJ_528', '<a href=MP3_Peter/ZJ_528-Gedenken_wij_dankbaar.mp3>                         <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_528-Gedenken_wij_dankbaar'                                 ],
    ['ZJ_529', '<a href=MP3_Peter/ZJ_529-Gij_dienaars_aan_de_Heer_gewijd.mp3>               <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_529-Gij_dienaars_aan_de_Heer_gewijd'                       ],
    ['ZJ_530', '<a href=MP3_Peter/ZJ_530-Zo_vriendelijk_en_veilig.mp3>                      <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_530-Zo_vriendelijk_en_veilig'                              ],
    ['ZJ_531', '<a href=MP3_Peter/ZJ_531-God_die_ons_heeft_voorzien.mp3>                    <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_531-God_die_ons_heeft_voorzien'                            ],
    ['ZJ_532', '<a href=MP3_Peter/ZJ_532-O_Heer_die_overwint.mp3>                           <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_532-O_Heer_die_overwint'                                   ],
    ['ZJ_533', '<a href=MP3_Peter/ZJ_533-Iedere_tijd_opnieuw.mp3>                           <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_533-Iedere_tijd_opnieuw'                                   ],
    ['ZJ_534', '<a href=MP3_Peter/ZJ_534-Wie_naar_het_altaar_gaat.mp3>                      <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_534-Wie_naar_het_altaar_gaat'                              ],
    ['ZJ_535', '<a href=MP3_Peter/ZJ_535-Het_brood_het_goede_brood.mp3>                     <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_535-Het_brood_het_goede_brood'                             ],
    ['ZJ_537', '<a href=MP3_Peter/ZJ_537-God_geeft_gesproken_in_de_tijd.mp3>                <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_537-God_geeft_gesproken_in_de_tijd'                        ],
    ['ZJ_539', '<a href=MP3_Peter/ZJ_539-Dit_lied_gaat_over_Jezus.mp3>                      <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_539-Dit_lied_gaat_over_Jezus'                              ],
    ['ZJ_540', '<a href=MP3_Peter/ZJ_540-Heer_onze_Heer_hoe_zijt_Gij_aanwezig.mp3>          <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_540-Heer_onze_Heer_hoe_zijt_Gij_aanwezig'                  ],
    ['ZJ_541', '<a href=MP3_Peter/ZJ_541-God_heeft_het_eerste_woord.mp3>                    <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_541-God_heeft_het_eerste_woord'                            ],
    ['ZJ_543', '<a href=MP3_Peter/ZJ_543-Zeven_was_voldoende.mp3>                           <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_543-Zeven_was_voldoende'                                   ],
    ['ZJ_544', '<a href=MP3_Peter/ZJ_544-Ik_zal_zolang_ik_leef.mp3>                         <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_544-Ik_zal_zolang_ik_leef'                                 ],
    ['ZJ_545', '<a href=MP3_Peter/ZJ_545-Wij_willen_samen_vieren.mp3>                       <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_545-Wij_willen_samen_vieren'                               ],
    ['ZJ_546', '<a href=MP3_Peter/ZJ_546-Hij_nam_de_Schrift.mp3>                            <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_546-Hij_nam_de_Schrift'                                    ],
    ['ZJ_547', '<a href=MP3_Peter/ZJ_547-Het_brood_in_de_aarde.mp3>                         <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_547-Het_brood_in_de_aarde'                                 ],
    ['ZJ_548', '<a href=MP3_Peter/ZJ_548-Zo_lief_heeft_God_de_wereld.mp3>                   <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_548-Zo_lief_heeft_God_de_wereld'                           ],
    ['ZJ_549', '<a href=MP3_Peter/ZJ_549-Dit_huis_gerenigd_en_versierd.mp3>                 <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_549-Dit_huis_gerenigd_en_versierd'                         ],
    ['ZJ_550', '<a href=MP3_Peter/ZJ_550-Welzalig_wie_de_rechte_wegen_gaan.mp3>             <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_550-Welzalig_wie_de_rechte_wegen_gaan'                     ],
    ['ZJ_551', '<a href=MP3_Peter/ZJ_551-De_heiligen_ons_voorgegaan.mp3>                    <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_551-De_heiligen_ons_voorgegaan'                            ],
    ['ZJ_552', '<a href=MP3_Peter/ZJ_552-Voor_de_toegewijden.mp3>                           <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_552-Voor_de_toegewijden'                                   ],
    ['ZJ_553', '<a href=MP3_Peter/ZJ_553-Waarlijk_dit_is_rechtvaardig.mp3>                  <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_553-Waarlijk_dit_is_rechtvaardig'                          ],
    ['ZJ_554', '<a href=MP3_Peter/ZJ_554-God_groet_u_zuiver_bloeme.mp3>                     <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_554-God_groet_u_zuiver_bloeme'                             ],
    ['ZJ_556', '<a href=MP3_Peter/ZJ_556-Wachters_van_de_tijd.mp3>                          <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_556-Wachters_van_de_tijd'                                  ],
    ['ZJ_557', '<a href=MP3_Peter/ZJ_557-Maria_schone_Vrouwe.mp3>                           <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_557-Maria_schone_Vrouwe'                                   ],
    ['ZJ_558', '<a href=MP3_Peter/ZJ_558-Maria_poort_van_Gods_genade.mp3>                   <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_558-Maria_poort_van_Gods_genade'                           ],
    ['ZJ_559', '<a href=MP3_Peter/ZJ_559-De_Heer_heeft_mij_gezien.mp3>                      <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_559-De_Heer_heeft_mij_gezien'                              ],
    ['ZJ_560', '<a href=MP3_Peter/ZJ_560-Zalig_zij_die_Jezus_naam_belijden.mp3>             <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_560-Zalig_zij_die_Jezus_naam_belijden'                     ],
    ['ZJ_561', '<a href=MP3_Peter/ZJ_561-Wij_zijn_uw_volk.mp3>                              <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_561-Wij_zijn_uw_volk'                                      ],
    ['ZJ_562', '<a href=MP3_Peter/ZJ_562-Jezus_die_langs_het_water_liep.mp3>                <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_562-Jezus_die_langs_het_water_liep'                        ],
    ['ZJ_563', '<a href=MP3_Peter/ZJ_563-Heer_Gij_zijt_burcht_en_toren.mp3>                 <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_563-Heer_Gij_zijt_burcht_en_toren'                         ],
    ['ZJ_563', '<a href=MP3_Peter/ZJ_563-Heer_Gij_zijt_burcht_en_toren_v2.mp3>              <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_563-Heer_Gij_zijt_burcht_en_toren_v2'                      ],
    ['ZJ_564', '<a href=MP3_Peter/ZJ_564-Weest_niet_bezorgd.mp3>                            <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_564-Weest_niet_bezorgd'                                    ],
    ['ZJ_565', '<a href=MP3_Peter/ZJ_565-Ik_verheerlijk_de_Heer.mp3>                        <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_565-Ik_verheerlijk_de_Heer'                                ],
    ['ZJ_566', '<a href=MP3_Peter/ZJ_566-Hoe_is_uw_naam.mp3>                                <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_566-Hoe_is_uw_naam'                                        ],
    ['ZJ_567', '<a href=MP3_Peter/ZJ_567-Een_smekeling_zo_kom_ik_tot_uw_troon.mp3>          <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_567-Een_smekeling_zo_kom_ik_tot_uw_troon'                  ],
    ['ZJ_569', '<a href=MP3_Peter/ZJ_569-God_die_leven_hebt_gegeven.mp3>                    <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_569-God_die_leven_hebt_gegeven'                            ],
    ['ZJ_570', '<a href=MP3_Peter/ZJ_570-Gij_zijt_mijn_goed_mijn_overvloed.mp3>             <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_570-Gij_zijt_mijn_goed_mijn_overvloed'                     ],
    ['ZJ_571', '<a href=MP3_Peter/ZJ_571-Niet_als_een_storm.mp3>                            <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_571-Niet_als_een_storm'                                    ],
    ['ZJ_572', '<a href=MP3_Peter/ZJ_572-De_aarde_is_vervuld.mp3>                           <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_572-De_aarde_is_vervuld'                                   ],
    ['ZJ_575', '<a href=MP3_Peter/ZJ_575-Zolang_er_mensen_zijn_op_aarde.mp3>                <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_575-Zolang_er_mensen_zijn_op_aarde'                        ],
    ['ZJ_576', '<a href=MP3_Peter/ZJ_576-Bouwen_aan_een_wereld.mp3>                         <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_576-Bouwen_aan_een_wereld'                                 ],
    ['ZJ_578', '<a href=MP3_Peter/ZJ_578-Volk_van_God.mp3>                                  <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_578-Volk_van_God'                                          ],
    ['ZJ_579', '<a href=MP3_Peter/ZJ_579-Uw_koninkrijk_komt.mp3>                            <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_579-Uw_koninkrijk_komt'                                    ],
    ['ZJ_580', '<a href=MP3_Peter/ZJ_580-Zoals_een_hert_reikhalst.mp3>                      <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_580-Zoals_een_hert_reikhalst'                              ],
    ['ZJ_581', '<a href=MP3_Peter/ZJ_581-Mijn_God_zijt_Gij.mp3>                             <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_581-Mijn_God_zijt_Gij'                                     ],
    ['ZJ_583', '<a href=MP3_Peter/ZJ_583-Alles_wat_adem_heeft.mp3>                          <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_583-Alles_wat_adem_heeft'                                  ],
    ['ZJ_585', '<a href=MP3_Peter/ZJ_585-Dankt_dankt_nu_allen_God.mp3>                      <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_585-Dankt_dankt_nu_allen_God'                              ],
    ['ZJ_588', '<a href=MP3_Peter/ZJ_588-God_in_den_hoog_alleen.mp3>                        <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_588-God_in_den_hoog_alleen'                                ],
    ['ZJ_589', '<a href=MP3_Peter/ZJ_589-De_laatsten_worden_de_eersten.mp3>                 <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_589-De_laatsten_worden_de_eersten'                         ],
    ['ZJ_590', '<a href=MP3_Peter/ZJ_590-De_eersten_zijn_de_laatsten.mp3>                   <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_590-De_eersten_zijn_de_laatsten'                           ],
    ['ZJ_591', '<a href=MP3_Peter/ZJ_591-Mensen_wij_zijn_geroepen_om_te_leven.mp3>          <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_591-Mensen_wij_zijn_geroepen_om_te_leven'                  ],
    ['ZJ_593', '<a href=MP3_Peter/ZJ_593-Ga_in_het_schip.mp3>                               <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_593-Ga_in_het_schip'                                       ],
    ['ZJ_594', '<a href=MP3_Peter/ZJ_594-Wie_oren_om_te_horen_heeft.mp3>                    <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_594-Wie_oren_om_te_horen_heeft'                            ],
    ['ZJ_595', '<a href=MP3_Peter/ZJ_595-Mijn_ziel_maakt_groot_de_Heer.mp3>                 <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_595-Mijn_ziel_maakt_groot_de_Heer'                         ],
    ['ZJ_596', '<a href=MP3_Peter/ZJ_596-Een_zaaier_ging_uit.mp3>                           <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_596-Een_zaaier_ging_uit'                                   ],
    ['ZJ_597', '<a href=MP3_Peter/ZJ_597-Gij_hebt_met_uw_brede_gebaren.mp3>                 <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_597-Gij_hebt_met_uw_brede_gebaren'                         ],
    ['ZJ_598', '<a href=MP3_Peter/ZJ_598-De_schapen_alle_honderd.mp3>                       <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_598-De_schapen_alle_honderd'                               ],
    ['ZJ_599', '<a href=MP3_Peter/ZJ_599-Looft_uwe_God_alle_tongen_en_talen.mp3>            <img src="src/mp3.png" width="20" height="20"> </a>','ZJ_599-Looft_uwe_God_alle_tongen_en_talen'                    ],
    [' ',  ' ' , ' ' ]
];

function createTable(dataMP3Peter500) {
  const [headings, ...rows] = dataMP3Peter500;
      
    return `
          <table>
            <thead>${getCells(headings, 'th')}</thead>
            <tbody>${rows.map(getRow).join('')}</tbody>
          </table>
    `;
}

document.body.insertAdjacentHTML('beforeend', createTable(dataMP3Peter500));
